apiVersion: v1
kind: Service
metadata:
  name: backstage
  labels:
    app: backstage
spec:
  type: ClusterIP
  selector:
    app: backstage
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: http
