apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: ${{ values.artifactId }}-api
  {%- if values.description %}
  description: ${{ values.description | dump }}
  {%- endif %}
spec:
  type: openapi
  lifecycle: experimental
  owner: ${{ values.owner }}
  definition:
    #   $text: https://github.com/OAI/OpenAPI-Specification/blob/main/examples/v3.0/petstore.yaml
    $text: src/main/resources/static/openapi.yaml
---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: ${{ values.artifactId }}-db
  {%- if values.description %}
  description: ${{ values.description | dump }}
  {%- endif %}
spec:
  type: database
  lifecycle: experimental
  owner: ${{ values.owner }}
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.artifactId }}
  {%- if values.description %}
  description: ${{ values.description | dump }}
  {%- endif %}
  annotations:
    backstage.io/techdocs-ref: dir:.
  links:
    - url: https://example.com/user
      title: Examples Users
      icon: user
  tags:
    - java
    - spring
spec:
  #type: ${{ values.metadata.type | dump }} # Still empty?
  type: service
  lifecycle: experimental
  owner: ${{ values.owner }}
  dependsOn:
    - resource:${{ values.artifactId }}-db
  providesApis:
    - ${{ values.artifactId }}-api