app:
  # Should be the same as backend.baseUrl when using the `app-backend` plugin
  baseUrl: http://localhost:7007

backend:
  baseUrl: http://localhost:7007
  listen:
    port: 7007

catalog:
  locations:
    # Backstage example components
    - type: url
      target: https://github.com/backstage/backstage/blob/master/packages/catalog-model/examples/all-components.yaml

    # Backstage example systems
    - type: url
      target: https://github.com/backstage/backstage/blob/master/packages/catalog-model/examples/all-systems.yaml

     # Backstage example domains
    - type: url
      target: https://github.com/backstage/backstage/blob/master/packages/catalog-model/examples/all-domains.yaml

    # Backstage example APIs
    - type: url
      target: https://github.com/backstage/backstage/blob/master/packages/catalog-model/examples/all-apis.yaml

    # Backstage example resources
    - type: url
      target: https://github.com/backstage/backstage/blob/master/packages/catalog-model/examples/all-resources.yaml

    # Backstage example groups and users
    - type: url
      target: https://github.com/backstage/backstage/blob/master/packages/catalog-model/examples/acme-corp.yaml

    # Backstage example templates
    - type: url
      target: https://github.com/backstage/software-templates/blob/main/scaffolder-templates/react-ssr-template/template.yaml

    - type: url
      target: https://github.com/backstage/software-templates/blob/main/scaffolder-templates/springboot-grpc-template/template.yaml

    - type: url
      target: https://github.com/backstage/software-templates/blob/main/scaffolder-templates/docs-template/template.yaml

    # Custom Componentes
    - type: url
      target: https://github.com/jsa4000/Internal-Development-Platform/blob/main/catalog-info.yaml
    
    # Custom Templates
    - type: url
      target: https://github.com/jsa4000/Internal-Development-Platform/blob/main/samples/templates/hello-world-template/template.yaml

    - type: url
      target: https://github.com/jsa4000/Internal-Development-Platform/blob/main/samples/templates/jsonschema-template/template.yaml

    - type: url
      target: https://github.com/jsa4000/Internal-Development-Platform/blob/main/samples/templates/springboot-grpc-template/template.yaml

    - type: url
      target: https://github.com/jsa4000/Internal-Development-Platform/blob/main/samples/templates/yeoman-nitro-template/template.yaml

    - type: url
      target: https://github.com/jsa4000/Internal-Development-Platform/blob/main/samples/templates/yeoman-java-template/template.yaml

