apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: custom-system
  description: Custom System
spec:
  owner: custom-owner
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: custom-api
  description: The official backstage REST API
spec:
  type: openapi
  lifecycle: production
  owner: custom-owner
  system: custom-system
  definition:
#   $text: https://github.com/OAI/OpenAPI-Specification/blob/main/examples/v3.0/petstore.yaml
    $text: apis/petstore.yaml
---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: custom-db
  description: Stores custom-app data
spec:
  type: database
  lifecycle: production
  owner: custom-owner
  system: custom-system
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: custom-app
  description: This is a custom Component Application
  links:
    - url: https://example.com/user
      title: Examples Users
      icon: user
    - url: https://example.com/group
      title: Example Group
      icon: group
    - url: https://example.com/cloud
      title: Link with Cloud Icon
      icon: cloud
    - url: https://example.com/dashboard
      title: Dashboard
      icon: dashboard
    - url: https://example.com/help
      title: Support
      icon: help
    - url: https://example.com/web
      title: Website
      icon: web
    - url: https://example.com/alert
      title: Alerts
      icon: alert
  annotations:
    github.com/project-slug: jsa4000/backstage-example
    backstage.io/techdocs-ref: dir:.
  tags:
    - java
    - spring
spec:
  type: service
  lifecycle: production
  owner: custom-owner
  system: custom-system
  dependsOn: 
  - resource:custom-db
  providesApis:
  - custom-api
