apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ${{ values.artifactId }}
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "10"
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  #project: ${{ values.owner }}
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: ${{ values.namespace }}
  source:
    path: ${{ values.targetPath }} 
    repoURL: ${{ values.repoUrl }} 
    targetRevision: ${{ values.branch }} 
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
        - CreateNamespace=true