apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.name }}
  {%- if values.description %}
  description: ${{ values.description | dump }}
  {%- endif %}
  annotations:
    backstage.io/techdocs-ref: dir:.
  links:
    - url: https://example.com/user
      title: Examples Users
      icon: user
  tags:
    - ${{ values.tech }}
spec:
  type: ${{ values.type }}
  lifecycle: experimental
  owner: ${{ values.owner }}
