version: '3.8'
services:
  postgresql:
    image: postgres:14.2
    # volumes:
    #   - ~/volumes/postgresql/data/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - 5432:5432
