apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: project-initializer-template
  title: Project Initializer Template
  description: Create a base repository for a project
  tags:
    - recommended
    - java
    - rest
    - openapi
spec:
  owner: user:jsa4000
  type: service

  parameters:
    - title: Provide some Project Metadata
      required:
        - groupId
        - artifactId
        - name
        - owner
      properties:
        name:
          title: name
          type: string
          pattern: "^[a-zA-Z0-9-]*$"
          minLength: 2
          maxLength: 128
          description: Unique name of the Project
          default: app
        description:
          title: Description
          type: string
          description: Description of the Project
          default: Demo project for Spring Boot
        githubAccount:
          title: Github Account
          type: string
          default: jsa4000
          ui:disabled: true
        owner:
          title: Owner
          type: string
          description: Owner of the Component
          ui:field: OwnerPicker
          ui:options:
            allowedKinds:
              - Group
              - User

  steps:
    - id: template
      name: Fetch Skeleton + Template
      action: fetch:template
      input:
        url: ./skeleton
        values:
          name: ${{ parameters.name  | lower }}
          description: ${{ parameters.description }}
          owner: ${{ parameters.owner }}

    - id: publish
      name: Publish
      action: publish:github
      input:
        allowedHosts: ["github.com"]
        description: ${{ parameters.description }}
        repoUrl: github.com?owner=${{ parameters.githubAccount }}&repo=${{ parameters.name | lower }}-service-java

    - id: register
      name: Register
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps.publish.output.repoContentsUrl }}
        catalogInfoPath: "/catalog-info.yaml"

  output:
    links:
      - title: Repository
        url: ${{ steps.publish.output.remoteUrl }}
      - title: Open in catalog
        icon: catalog
        entityRef: ${{ steps.register.output.entityRef }}
