apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: project-initializer-template
  title: Project Initializer Template
  description: Create a base repository for a project
  tags:
    - recommended
    - java
    - rest
    - openapi
spec:
  owner: user:jsa4000
  type: service

  parameters:
    - title: Provide some Project Metadata
      required:
        - name
        - owner
      properties:
        name:
          title: name
          type: string
          pattern: "^[a-zA-Z0-9-]*$"
          minLength: 2
          maxLength: 128
          description: Unique name of the Project
          default: app
        description:
          title: Description
          type: string
          maxLength: 256
          description: Description of the Project
          default: This is a description of the Project
        metadata:
          title: Project Metadata
          type: object
          properties:
            type:
              title: Project Type
              description: Select the Type of Project to be Generated
              type: string
              enum:
              - service
              - webapp
              - library
              - api
              - gitops
              - config
              default: service
          required:
          - type
          dependencies:
            type:
              oneOf:
              - properties:
                  type:
                    enum:
                    - service
                  tech:
                    title: Technlogy
                    type: string
                    description: Select the Desired Technology for the Service
                    enum:
                    - java
                    - nodejs
                    - python
                    default: java
                required:
                - tech
              - properties:
                  type:
                    enum:
                    - webapp
                  tech:
                    title: Technlogy
                    type: string
                    description: Select the Desired Technology for the Webapp
                    enum:
                    - angular
                    - react
                    - vue
                    default: angular
                required:
                - tech
              - properties:
                  type:
                    enum:
                    - library
                  tech:
                    title: Technlogy
                    type: string
                    description: Select the Desired Technology for the Library
                    enum:
                    - java
                    - nodejs
                    - python
                    - angular
                    - react
                    - vue
                    default: java
                required:
                - tech
              - properties:
                  type:
                    enum:
                    - api
                  tech:
                    title: Technlogy
                    type: string
                    description: Select the Desired Technology for the API
                    enum:
                    - openapi
                    - asyncapi
                    - graphql
                    default: openapi
                required:
                - tech
              - properties:
                  type:
                    enum:
                    - gitops
                  tech:
                    title: Technlogy
                    type: string
                    description: Select the Desired Technology for GitOps
                    enum:
                    - argocd
                    - flux
                    default: argocd
                required:
                - tech
              - properties:
                  type:
                    enum:
                    - config
                  tech:
                    title: Technlogy
                    type: string
                    description: Select the Desired Technology for the Configuration
                    enum:
                    - helm
                    - dockerfile
                    - manifests
                    - kustomize
                    default: helm
                required:
                - tech
        githubAccount:
          title: Github Account
          type: string
          default: jsa4000
          ui:disabled: true
        owner:
          title: Owner
          type: string
          description: Owner of the Project
          ui:field: OwnerPicker
          ui:options:
            allowedKinds:
              - Group

  steps:
    - id: template
      name: Fetch Skeleton + Template
      action: fetch:template
      input:
        url: ./skeleton
        values:
          name: ${{ parameters.name  | lower }}
          type: ${{ parameters.metadata.type  | lower }}
          tech: ${{ parameters.metadata.tech  | lower }}
          description: ${{ parameters.description }}
          owner: ${{ parameters.owner }}

    - id: publish
      name: Publish
      action: publish:github
      input:
        allowedHosts: ["github.com"]
        description: ${{ parameters.description }}
        repoUrl: github.com?owner=${{ parameters.githubAccount }}&repo=${{ parameters.name | lower }}-${{ parameters.owner | lower }}-${{ parameters.metadata.type }}-${{ parameters.metadata.tech }}

    - id: register
      name: Register
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps.publish.output.repoContentsUrl }}
        catalogInfoPath: "/catalog-info.yaml"

  output:
    links:
      - title: Repository
        url: ${{ steps.publish.output.remoteUrl }}
      - title: Open in catalog
        icon: catalog
        entityRef: ${{ steps.register.output.entityRef }}
